name: Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Auto-increment version and create a release
      uses: actions-ecosystem/action-bump-semver@v1
      id: bump-semver
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        semver_level: minor
        create_tag: true

    - name: Create a GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ steps.bump-semver.outputs.new_tag }}
        release_name: Release ${{ steps.bump-semver.outputs.new_tag }}
        body: |
          Changes in this release:
          - ${{ steps.bump-semver.outputs.changes }}
        draft: false
        prerelease: false
